version: '3.3'

services:
  web:
    build: .
    command: nodemon index.js
    volumes:
      - .:/opt/app
      - notused:/opt/app/node_modules
    environment:
      NODE_ENV: development

volumes:
  notused:
