version: '3.3'

services:
  web:
    image: muryginm/chat:latest
    environment:
      REDIS_HOST: redis
      REDiS_PORT: 6379
    ports:
      - 80:80
    depends_on:
      - redis

  redis:
    image: redis:4.0.2
